pipeline {
    agent any
    options {
        skipDefaultCheckout(true)
    }
    tools { nodejs "20.15.0"}
    triggers {
        pollSCM('H 9,12,17 * * *')
    }
    stages {
        stage ('clean workspace') {
            steps {
                echo 'Cleaning workspace...'
                cleanWs()
                echo 'Cleaning done'
            } 
        }
        stage ('clone') {
            steps {
                echo 'Cloning...'
                // checkout scm
                git branch: 'S11P12D202-810-we-멀티-프로필-관리', credentialsId: 'gitlab-repo', url: 'https://lab.ssafy.com/s11-webmobile1-sub2/S11P12D202.git'
                echo 'Cloning done'
            }
        }
        stage('FE-Build') {
            steps {
                echo "FE Building.."
                dir('./frontend') {
                    withCredentials([file(credentialsId: 'frontend-env', variable: 'ENV_FILE')]) {
                        sh 'cat $ENV_FILE > .env'
                    }
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
        stage('FE-Delivery') {
            steps {
                dir('./frontend') {
                    echo "Delivery FE Image.."
                    withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin"
                        sh "docker build -t $DOCKER_USERNAME/moducha_frontend:${env.BUILD_ID} ."
                        sh "docker tag $DOCKER_USERNAME/moducha_frontend:${env.BUILD_ID} $DOCKER_USERNAME/moducha_frontend:latest"
                        sh "docker push $DOCKER_USERNAME/moducha_frontend:${env.BUILD_ID}"
                        sh "docker push $DOCKER_USERNAME/moducha_frontend:latest"
                    }
                }
            }
        }
        // stage('BE-Build') {
        //     steps {
        //         echo "BE Building.."
        //         dir('./backend') {
        //             sh '''
        //             ./gradlew clean build -x test
        //             '''
        //         }
        //     }
        // }
    //     stage('BE-Delivery') {
    //         steps {
    //             dir('./backend') {
    //                 echo "Delivery BE Image.."
    //                 withCredentials([string(credentialsId: 'github-oauth-token', variable: 'GITHUB_OAUTH_TOKEN')]) {
    //                     sh '''
    //                     docker login -u $DOCKER_ID -p $GITHUB_OAUTH_TOKEN
    //                     docker.build("${DOCKER_ID}/moducha_backend:${env.BUILD_ID}")
    //                     docker.tag("${DOCKER_ID}/moducha_backend:${env.BUILD_ID}", "${DOCKER_ID}/moducha_backend:latest")
    //                     docker.push("${DOCKER_ID}/moducha_backend:${env.BUILD_ID}")
    //                     docker.push("${DOCKER_ID}/moducha_backend:latest")
    //                     '''
    //                 }
    //             }
    //         }
    //     }
    // stage('Deploy to EC2-FE') {
    //     steps {
    //         echo '프론트 EC2에 배포 시작!'
    //         // 여기에서는 SSH 플러그인이나 SSH 스크립트를 사용하여 EC2로 연결하고 Docker 컨테이너 실행
    //         sshagent(['aws-key']) { 
    //             sh "docker rm -f frontend"
    //             sh "docker rmi osy9536/ssafy-fe:latest"
    //             sh "docker image prune -f"
    //             sh "docker pull osy9536/ssafy-fe:latest && docker run -d -p 3000:3000 --name frontend osy9536/ssafy-fe:latest"
    //         }
    //         echo '프론트 EC2에 배포 완료!'
    //     } 
    // }
    }
    post {
        always {
            cleanWs(cleanWhenNotBuilt: false, deleteDirs: true, 
            disableDeferredWipeout: true, notFailBuild: true)
        }
    }
}