import translations from 'ckeditor5/translations/ko.js';
import {
  AccessibilityHelp,
  Autosave,
  Bold,
  Essentials,
  FontBackgroundColor,
  FontColor,
  FontFamily,
  FontSize,
  Italic,
  Paragraph,
  SelectAll,
  Underline,
  Undo,
} from 'ckeditor5';
const editorConfig = {
  toolbar: {
    items: [
      'undo',
      'redo',
      '|',
      'selectAll',
      '|',
      'fontSize',
      'fontFamily',
      'fontColor',
      'fontBackgroundColor',
      '|',
      'bold',
      'italic',
      'underline',
      '|',
      'accessibilityHelp',
    ],
    shouldNotGroupWhenFull: false,
  },
  plugins: [
    AccessibilityHelp,
    Autosave,
    Bold,
    Essentials,
    FontBackgroundColor,
    FontColor,
    FontFamily,
    FontSize,
    Italic,
    Paragraph,
    SelectAll,
    Underline,
    Undo,
  ],
  fontFamily: {
    supportAllValues: true,
  },
  fontSize: {
    options: [10, 12, 14, 'default', 18, 20, 22],
    supportAllValues: true,
  },
  initialData: '가나다라마바사',
  language: 'ko',
  placeholder: 'Type or paste your content here!',
  translations: [translations],
};
export default editorConfig;
